/* tslint:disable */
/* eslint-disable */
/**
 * Backend for Docker containers ping info service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ContainerInfo
 */
export interface ContainerInfo {

    /**
     * @type {string}
     * @memberof ContainerInfo
     */
    ip: string;

    /**
     * @type {Date}
     * @memberof ContainerInfo
     */
    lastPing?: Date;

    /**
     * @type {Date}
     * @memberof ContainerInfo
     */
    lastSuccess?: Date;
}
