/* tslint:disable */
/* eslint-disable */
/**
 * Backend for Docker containers ping info service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ContainerInfo
 */
export interface ContainerInfo {
    /**
     * 
     * @type {string}
     * @memberof ContainerInfo
     */
    'ip': string;
    /**
     * 
     * @type {string}
     * @memberof ContainerInfo
     */
    'last_ping'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContainerInfo
     */
    'last_success'?: string;
}
/**
 * 
 * @export
 * @interface PingInfo
 */
export interface PingInfo {
    /**
     * 
     * @type {string}
     * @memberof PingInfo
     */
    'container_ip': string;
    /**
     * 
     * @type {string}
     * @memberof PingInfo
     */
    'timestamp': string;
    /**
     * 
     * @type {boolean}
     * @memberof PingInfo
     */
    'success': boolean;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Получить информацию о контейнерах и их последнем пинге
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsAggregateGet: async (oldestFirst?: boolean, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pings/aggregate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (oldestFirst !== undefined) {
                localVarQueryParameter['oldest_first'] = oldestFirst;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Получить информацию о пингах
         * @param {string} [containerIp] IP контейнера, для которого выдавать список пингов
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {boolean} [success] Возвращать только успешные или неудавшиеся записи
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsGet: async (containerIp?: string, oldestFirst?: boolean, success?: boolean, limit?: number, offset?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/pings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (containerIp !== undefined) {
                localVarQueryParameter['container_ip'] = containerIp;
            }

            if (oldestFirst !== undefined) {
                localVarQueryParameter['oldest_first'] = oldestFirst;
            }

            if (success !== undefined) {
                localVarQueryParameter['success'] = success;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Загрузить информацию о пингах
         * @param {Array<PingInfo>} pingInfo Список результатов пинга
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsPut: async (pingInfo: Array<PingInfo>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pingInfo' is not null or undefined
            assertParamExists('pingsPut', 'pingInfo', pingInfo)
            const localVarPath = `/pings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pingInfo, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Получить информацию о контейнерах и их последнем пинге
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsAggregateGet(oldestFirst?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContainerInfo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingsAggregateGet(oldestFirst, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pingsAggregateGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Получить информацию о пингах
         * @param {string} [containerIp] IP контейнера, для которого выдавать список пингов
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {boolean} [success] Возвращать только успешные или неудавшиеся записи
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsGet(containerIp?: string, oldestFirst?: boolean, success?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PingInfo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingsGet(containerIp, oldestFirst, success, limit, offset, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pingsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Загрузить информацию о пингах
         * @param {Array<PingInfo>} pingInfo Список результатов пинга
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pingsPut(pingInfo: Array<PingInfo>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pingsPut(pingInfo, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.pingsPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Получить информацию о контейнерах и их последнем пинге
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsAggregateGet(oldestFirst?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContainerInfo>> {
            return localVarFp.pingsAggregateGet(oldestFirst, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Получить информацию о пингах
         * @param {string} [containerIp] IP контейнера, для которого выдавать список пингов
         * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
         * @param {boolean} [success] Возвращать только успешные или неудавшиеся записи
         * @param {number} [limit] Максимальное количество выдаваемых результатов
         * @param {number} [offset] Количество результатов, которое необходимо пропустить
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsGet(containerIp?: string, oldestFirst?: boolean, success?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<PingInfo>> {
            return localVarFp.pingsGet(containerIp, oldestFirst, success, limit, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Загрузить информацию о пингах
         * @param {Array<PingInfo>} pingInfo Список результатов пинга
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pingsPut(pingInfo: Array<PingInfo>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.pingsPut(pingInfo, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Получить информацию о контейнерах и их последнем пинге
     * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
     * @param {number} [limit] Максимальное количество выдаваемых результатов
     * @param {number} [offset] Количество результатов, которое необходимо пропустить
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pingsAggregateGet(oldestFirst?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pingsAggregateGet(oldestFirst, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Получить информацию о пингах
     * @param {string} [containerIp] IP контейнера, для которого выдавать список пингов
     * @param {boolean} [oldestFirst] Сортировать начиная со старых записей
     * @param {boolean} [success] Возвращать только успешные или неудавшиеся записи
     * @param {number} [limit] Максимальное количество выдаваемых результатов
     * @param {number} [offset] Количество результатов, которое необходимо пропустить
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pingsGet(containerIp?: string, oldestFirst?: boolean, success?: boolean, limit?: number, offset?: number, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pingsGet(containerIp, oldestFirst, success, limit, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Загрузить информацию о пингах
     * @param {Array<PingInfo>} pingInfo Список результатов пинга
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public pingsPut(pingInfo: Array<PingInfo>, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).pingsPut(pingInfo, options).then((request) => request(this.axios, this.basePath));
    }
}



